= Context-driven approach to automation in testing (정리)
:author:    여용구(QA)


NOTE: https://www.google.co.kr/url?sa=t&rct=j&q=&esrc=s&source=web&cd=1&cad=rja&uact=8&ved=0ahUKEwiI1bC9isfLAhUC4qYKHaEeBgwQFggbMAA&url=http%3A%2F%2Fwww.satisfice.com%2Farticles%2Fcdt-automation.pdf&usg=AFQjCNHa0qcBtDtsMdJTn8aNk1hvLswIqQ&sig2=knKPmJ4b8a7BtSpLP1J_yg[A Context-Driven Approach to Automation in Testing] (By James Bach and Michael Bolton, 2016 2월)의 내용 중 일부 요약

* 좋은 테스팅이 필요하다면, 좋은 툴 지원이 그림에 포함되어야 한다.

* 자동화에 들어가는 대부분의 노력은 직접 사람이 제품을 다양하고 복잡한 방식으로 상호작용하는 데에 노력을 들이는것이 더 낫다고 생각한다. 그러면서 비용이 덜 들어가는 툴을 지원하는 것이 테스터가 테스트를 더 잘할 수 있도록 돕는 것이라고 믿는다.

."테스트 자동화"가 아니라 "툴"이라 부르기
* 테스트는 제품의 가져야하는 진짜 상태(true status)를 찾아내는 것이다.
* 테스터는 sensemaking, 비판적 사고, 실험을 하면서 임하는데, 기계적인 방법으로는 어떠한 것도 달성할 수 없는 것이다.
* 어떤 테스터이든 알지못하는 기대나 인식할 수 없는 행동을 적어놓을 수 없다. 때문에 사람이 실제로 하는 테스팅은 words로 바꿀수 없고, 이는 인코드 될 수 없고 자동화될수 없는 것이다. 고품질의 제품이나 서비스를 생산하기 위해서는, 테스팅 미션을 충족시킬수 있는 적절한 툴을 사용하는 skilled people이 필요하다.

.output checking을 훨씬 능가하는 testing으로 생각하기
* 테스팅은 실험(experimentation)과 탐색(exploration)을 통해 제품에 대해 배워감으로써 제품을 평가하는 것이라 생각한다. 여기에는 정도는 다르겠지만 질문, 공부, 모델링, 관찰 등이 포함된다.
* 테스팅은 incremental, speculative(사색적인), self-directed 탐색이 필수적인 프로세스이다.

* 테스팅은 다음과 같이 세분화 된다.
** 설계, 제품과 상호작용, 평가하기, 기록하고 보고하기,관리하기.

* checking과 testing의 구분
** checking은 알고리즘을 갖는 결정 규칙을 사용하여 제품의 특정 부분을 평가하는 것을 말하며, 이는 완벽히 자동화 될 수 있다.
** 테스트를 하는 우리의 자세는 반드시 문제를 발견해내려고 하는 것이지, 문제가 없음을 증명하는 것은 아니다.
** 품질을 평가(evaluating)하는 것은  skillful, complex, non-algorithmic 탐색 그리고 판단을 요구하는 작업이다.
*** 이와 같은 작업은 툴의 지원을 받을 수도 있고 빠르게 하도록 해주지만, 툴 자체가 이를 수행해주는 것은 아니다.

WARNING: 좋은 checking은 testing의 서브셋이다. checking은 testing과 같지 않다. biting이 eating과 같지 않은 것과 같다.

.툴을 사용하는 다양한 방법에 대해 연구하기
* 설계
** produce test data (tools like spreadsheets; state-model generators; Monte Carlo
simulations; random number generators)
** obfuscate or cleanse production data for privacy reasons (data shufflers; name
replacers)
** generate interesting combinations of parameters (all-pairs or combinatorial data
generators)
** generate flows through the product that cover specific conditions (state-model or flow-
model path generators)
* 제품 사용하기(상호작용)
** set up and configure the product or test environments (like continuous deployment
tools; virtualization tools; or system cloning tools)
** submitting and timing transactions; perhaps for a long time; at high volume; under
stress (profiling and benchmarking tools)
** encode procedures like operating the product and comparing its outputs to calculated
results (this is automated checking).
** simulate software or hardware that has not been developed yet; or that we do not have
immediately available to us (mocking or stubbing tools)
** probe the internal state of the system and analyze traffic within it as testing is being
performed (instrumentation; log analysis; file or process monitors; debugging tools)
* 평가
** sort, filter, and parse output logs (text editors; spreadsheets; regular expressions)
** visualize output for comparative analysis (diffing, charting and graphing tools,
conditional output formatting)
** develop, adapt and apply oracles that help us recognize potential problems (source file
or output comparison tools; parallel or comparable algorithms; internal consistency
checks within the application; statistical analysis tools)
* 기록 및 보고
** record our activities and document our procedures (note-taking tools; video-recording
tools; built-in logging; word processing tools; user interaction recording tools)
** prepare reports for our clients (mind maps; word processors; spreadsheets;
presentation software)
* 테스트 작업 관리
** map out our strategies (mind maps, outline processors, word processors)
** identify what has and has not been covered by testing (coverage tools; profilers; log file
analysis)
** preserve information about our products, and to aid other people in future support and
development (wikis; knowledge bases; file servers)

* 툴이 테스트를 하는 것이 아니라, 툴은 테스트가 테스트 작업을 하도록 돕는 것이다. 툴이 중요하지만, 테스팅의 중심에는 각 개별 테스터의 마인드셋과 스킬셋이 반드시 있어야한다.

TIP: 'context'의 뜻은 책임을 갖고 있는 테스터의 결정에 영향을 주는 요소들의 셋이다.

* Context driven testing은 다음의 원칙을 갖는다.

. The value of any practice depends on its context.
. There are good practices in context, but there are no best practices.
. People, working together, are the most important part of any project’s context.
. Projects unfold over time in ways that are often not predictable.
. The product is a solution. If the problem isn’t solved, the product doesn’t work.
. Good software testing is a challenging intellectual process.
. Only through judgment and skill, exercised cooperatively throughout the entire project, are
we able to do the right things at the right times to effectively test our products.

 (번역하면)
 1. 프랙틱스의 가치는 컨텍스트에 의존한다.
 2. 컨텍스트에 따른 좋은 프랙틱스는 있지만, 베스트 프래틱스는 없다.
 3. 어떠한 프로젝트의 컨텍스트이든, 함께 일하는 사람이 가장 중요한 부분이다.
 4. 프로젝트는 다양하게 일정을 초과하게되는데 이는 주로 예측하기 어렵다.
 5. 제품은 솔루션이다. 문제가 해결되지 않았다면 제품은 동작하는 것이 아니다.
 6. 좋은 소프트웨어 테스팅은 도전적인 지적인 프로세스이다
 7. 프로젝트 전 과정 속에서 총체적으로 배우고 익힌 기술과 판단을 통해서만, 효과적인 테스트를 돕는 활동을 적시에 할 수 있게된다.

* 컨텍스트 드리븐하기 위해서는 컨텍스트가 변할 때마다 일하는 방법을 바꿀 수 있어야하고 이에 대한 준비가 되어있어야한다.

* 컨텍스트 드리븐한 툴 활용은 어떻게 해야는가?
** 주위의 상황을 읽고
** 문제에 대한 핵심(요소)를 발견하고
** 선택할 수 있는 옵션을 생성하고
** 옵션에 가중치를 주어
** 특정 옵션을 선택한 이유를 만들고
** 그리고 나서 그 옵션을 프랙틱스에 적용하고, 어떤 결과가 나타나는지 책임을 갖고 본다.

* 좀 더 다양한 상황에서 좀 더 많은 자유를 주는 툴에 대한 조사하기

. 특정 목적에 최적화 된 것 보다는 다양한 목적에 대해서도 적합한 툴
. 저렴하거나 무료인 툴
. 사람이 개입하고 제어할 수 있는 부분이 많은 툴
. 사람이 많고 액티브한 커뮤니티를 갖고 있는 툴
. 비전문가에게도 사용할 수 있는 툴
. 내가 직접 제어할 수 있는 부분이 많은 툴
. 많은 플랫폼에서도 사용가능한 툴
. 배포가 쉽고 광범위하게 되는 툴

* 제품은 툴을 통한 쉬운 스크립팅 인터페이스를 주기 용이해야하고, 툴을 통해 상태나 output관찰이 용이해야한다.

.툴 지원 테스팅의 실전!

* checking 없이 툴 사용하기
** 테스터는 테스팅에 필요한 각 부분마다 지원받을 수 있는 툴이 있을지 생각해야한다.
** 테스터가 필요할 때마다 팀에 toolsmith와 같은 기술을 갖고 있는 사람을 언제든 컨택할 수 있으면 좋다.

* 높은 커버리지와 강력항 오라클을 위해 패턴화된 데이터 생성에 지원하는 툴
** 테스터는 데이타를 사용할 뿐만 아니라, 흥미로운 데이타를 만드는데 사용되는 프로그램을 에디트 할수 있어야한다.

* checking 자동화
** 버그를 발견하지만 이는 자동화된 checking 때문은 아니다.
** checking을 자동화하는 것과 버그를 발견하는 것에는 큰 연관이 없다는 것을 알아야한다.

* 왜 GUI 인터랙션을 자동화하는 것이 그렇게 어려운가?
** GUI는 사람을 위해 디자인된 것이기 때문이다.
** GUI-level 스크립팅은 귀찮고 성가시다.

* 제품 변화에 따라 GUI checking 자동화를 탄력적으로 만들수는 있다. 하지만 큰 비용을 치른다.
** 진정한 테스터는 프로덕트 투어리스트가 아니다. 우리는 비평적으로 우리가 본 것을 판단한다.
** 자동화 checking이 좀더 저렴하고 강력하게 되는 컨텍스트는 있다. 제품이 테스터블하게 만들어지면된다. 스크립트가 용이한 인터페이스 및 파싱하기 쉬운 로그파일을 생성하는 등..

.자동화 활동은 전략(tactic)이지, 의식(ritual)이 아니다.
* 우리의 미션을 완수하기 위해서는, 작업을 위해 사용하는 애플리케이션 및 툴의 전체 스펙트럼에 대해 평가할 수 있어야한다.
